#!/usr/bin/env perl

use strict;
use warnings;

my $cross_dir = shift;
open (INPUT,"find -L $cross_dir -type f -name '*.flagstat' -print -exec cat \\{\\} \\; |");

my $line = <INPUT>;
my $mapping;
my $sample;
exit -1 unless $line;
while ($line) {
   if ($line =~ /\Q$cross_dir\E\/?(.*)\/([^\/]*)\.flagstat/) {
       print "Mapping $1 Sample $2\n";
   }
   $line = <INPUT>;
}





close (INPUT);

__DATA__
40552182 in total
0 QC failure
0 duplicates
37379490 mapped (92.18%)
40552182 paired in sequencing
20276091 read1
20276091 read2
36002940 properly paired (88.78%)
36549729 with itself and mate mapped
829761 singletons (2.05%)
414658 with mate mapped to a different chr
291626 with mate mapped to a different chr (mapQ>=5)

