#!/usr/bin/env perl
use strict;
use warnings;

my @files = `pgv-dev query usable-sequence-files -t '*Anoph*'`;
shift @files;

while (my $file_descr = shift @files) {
   chomp $file_descr;
   my (undef,$tag,undef,undef,undef,undef,$file) = split(/\t/,$file_descr);
   `ils -l $file`;
   unless ($?) {
     print $file,"\n";
     if ($tag ne 'NA') {
       print STDERR "Tag $tag not need for $file\n";
     }
   }
   elsif ($tag ne 'NA') {
     $file =~ s/nonhuman\.bam/nonhuman#${tag}.bam/;
     `ils -l $file`;
     unless ($?) {
       print $file,"\n";
     }
     else {
       $file =~ s/_nonhuman//;
       `ils -l $file`;
       unless ($?) {
         print $file,"\n";
       }
       else {
         print STDERR "Could not find $file with tag $tag\n";
       }
     }
   }
   else {
      $file =~ s/_nonhuman//;
      `ils -l $file`;
      if ($?) {
         print STDERR "Could not find $file\n";
      }
      else {
         print $file,"\n";
      }
   } 
  
}
