#!/usr/bin/env perl

use strict;
use warnings;

my ($in_sample,$out_sample) = @ARGV;

my $new_header_file = $out_sample . ".hdr";
my $old_header = `samtools view -H $in_sample`;
my @old_header_lines = split(/\n/,$old_header);

my $new_header = join("\t",qw(@HD VN:1.3 CO:coordinate)) . "\n"; 

$new_header .= join("\n", grep { index($_,'@PG') < 0 } @old_header_lines) . "\n";
$new_header .= join("\t",qw(@PG ID:bwa)) . "\n";

open(HDR,">$new_header_file");
print HDR $new_header;
close(HDR);

`samtools reheader $new_header_file $in_sample > $out_sample`;
if ($?) {
  die "fail to fix $in_sample into $out_sample";
}
unlink($new_header_file);

`samtools index $out_sample`;
if ($?) {
  die "fail to index $out_sample";
}
