.DELETE_ON_ERROR:

.PHONY: all 

ALL_SAMPLE_NAMES=[% cross.samples.all.keys.join(' ') %]
ALL_SAMPLES=$(addsuffix .bam,$(ALL_SAMPLE_NAMES))
ALL_INDEXES=$(addsuffix .bam.bai,$(ALL_SAMPLE_NAMES))
ALL_SAMPLES_AND_INDEXES=$(join $(ALL_SAMPLE), $(ALL_INDEXES))
ALL_INTERVALS=[% cross.intervals.values.join(' ') %]
CANDIDATE_SNPS_LIST=[% cross.resources.varfilter.candidateSNPs.list %]
REFERENCE=[% cross.resources.reference %]
RC_MINBQ=[% cross.readCounts.minBaseQ || 27 %]

%.bam.bai : %.bam
	pgv index-alignment -i $< -o $@

.PRECIOUS : %.bam.bai

[% FOREACH name IN cross.mappings.keys -%]
  [%- mapping = cross.mappings.$name -%]
  [%- mapping.name = name -%]
  [%- INCLUDE mapping.tt mapping = mapping -%]

.PHONY: [% mapping.name %]

[% mapping.name %] : [% mapping.name %]/DONE.ts

[% IF cross.makeCandidateSNPsList %]
  [% INCLUDE candidateSNPsList.tt %]
[% END %]

[%- END -%]

all: [% cross.mappings.keys.join(' ') %]

