OUTDIR=.
ALIGNMENTS_PATH=[% manifest.get_path('alignments') %]
SNPSDATA_PATH=[% manifest.get_path('snpsdata') %]
COVERAGE_PATH=[% manifest.get_path('coverage') %]
TMPDIR=[% manifest.get_path('temp') || './tmp' %]

PGV=[% program %]
[% candidateList = manifest.get_parameter('candidateSnpList') || 'all' %]
CANDIDATE_SNPS_LIST=[% candidateList %]
REFERENCE=[% manifest.get_reference %]
MAX_RANDOM_SLEEP=60

ALL_SAMPLE_NAMES=[% manifest.get_sample_ids.join(' ') %]
ALL_ALIGNMENTS=$(addprefix $(ALIGNMENTS_PATH)/,$(addsuffix .bam,$(ALL_SAMPLE_NAMES)))
ALL_INDEXES=$(addprefix $(ALIGNMENTS_PATH)/,$(addsuffix .bam.bai,$(ALL_SAMPLE_NAMES)))
ALL_ALIGNMENT_AND_INDEXES=$(join $(ALL_ALIGNMENTS), $(ALL_INDEXES))

GENOTYPER=MetaGenotyper

GENOTYPER_OPTIONS=\
[% INCLUDE genotyper_options %]


INTERVALS=$(shell cat ./interval.list)
INTERVALS_AT=$(subst :,@,$(INTERVALS))
INTERVAL_VCFS=$(addprefix $(TMPDIR)/all_,$(addsuffix .vcf,$(INTERVALS_AT)))

$(shell mkdir -p $(ALIGNMENTS_PATH) $(SNPSDATA_PATH) $(COVERAGE_PATH) $(TMPDIR))

.DELETE_ON_ERROR:

.PHONY: all variation alignments

all: variation

variation: $(OUTDIR)/all.vcf.gz

$(TMPDIR)/interval-vcf.list: ./interval.list
	cat $< | grep -v ^$$ | tr ":" "@" | awk '{ print "$(TMPDIR)/all_"$$0".vcf" }' > $@

$(OUTDIR)/all.vcf.gz: $(TMPDIR)/interval-vcf.list $(INTERVAL_VCFS)
	$(PGV) concat --vcf-files $< -r $(REFERENCE) -o $@.tmp
	gzip < $@.tmp > $@
	rm $@.tmp

.SECONDARY: $(INTERVAL_VCFS)
.PRECIOUS: $(INTERVALS_VCFS)

$(TMPDIR)/all_%.vcf: $(ALL_ALIGNMENTS) [% IF candidateList != 'all' %]$(CANDIDATE_SNPS_LIST)[% END %]
	$(PGV) genotype -g $(GENOTYPER) -r $(REFERENCE) $(addprefix -i ,$(ALL_ALIGNMENTS)) -l $(subst @,:,$*) $(GENOTYPER_OPTIONS) -o $@ 

alignments: init $(ALL_ALIGNMENTS)

init:
	@echo "Starting processing...."
	mkdir -p $(TMPDIR)

[% FOREACH sample_id IN manifest.get_sample_ids %]
[% INCLUDE sampleRules.inc sample_id = sample_id  | trim %]
[% END %]
	
%.bam.bai : %.bam
	$(PGV) index -i $< -o $@

.SECONDARY : %.bam.bai

[%- BLOCK genotyper_options -%]
[%- IF candidateList != 'all' -%]
	--rod csl,CSL=$(CANDIDATE_SNPS_LIST)\

[%- END -%]
[%- options = manifest.get_parameter('genotyper','options') -%]
[%- FOREACH k IN options.keys -%]
 [%- v = options.$k -%]
 [%- IF v.size == 1 -%]
 	--option '[% k %]=[% v %]'\

 [%- ELSE -%]
	--option '[% k %]=[% v.join(',') %]'\

 [%- END -%]
[%- END -%]
[%- END -%]

