#!/usr/bin/env perl

use strict;
use warnings;

use File::Basename qw(dirname);
use Getopt::Long;

my $revision = 'HEAD';

GetOptions("r=s" => \$revision);

my $new_url = shift or die "you need to specify a subversion url";
my $dir = shift or die "you need to specify a destination directory";

if (-e $dir) {
  -d $dir or die "destination directory '$dir' is in fact not a directory";
}
else {
  my $parent = dirname($dir);
  -e $parent or die "the parent of the destination directory '$dir' does not exists";
  -d $parent or die "the parent of the destination directory '$dir' is not in fact a directory";
  print STDERR "svn co --revision $revision $new_url $dir\n";
  exec("svn co --non-interactive --trust-server-cert --revision $revision $new_url $dir");
}

my $what_to_do = undef;
my $svn_info = `svn info $dir`;
my $svn_url = undef;
my $svn_base = undef;
my $svn_branch = undef;
if ($?) {
  opendir(my $dest_dh,$dir) or die "could not open directory '$dir' for reading";
  my @non_trivial_entries = grep { $_ !~ /^\.+$/ } readdir($dest_dh);
  $#non_trivial_entries < 0 or die "the destination directory is not an svn working directory neither is empty, aborting!"; 
}
elsif ($svn_info =~ /^\s*URL:\s*(.+)\s*$/m) {
  $svn_url = $1;
  ($svn_base,$svn_branch) = split_svn_url($svn_url);
}
else {
  $svn_info =~ tr/\n/;/;
  die "could not determine the url of the svn checkout at '$dir'. The information stracted follows:\n\t" . $svn_info;
}

my ($new_base,$new_branch) = split_svn_url($new_url);


if ($new_base eq $svn_base) {
  if ($new_branch eq $svn_branch) {
     if ($svn_info =~ /^\s*Revision:\s*(\d+)\s*$/m) {
        if ($revision eq $1) {
           exit 0; # already in the right revision
        }
     }
     print STDERR "svn update --revision $revision $dir\n";
     exec("svn update --revision $revision $dir");
  }
  else {
     print STDERR "svn switch --revision $new_url $dir\n";
     exec("svn switch --revision $new_url $dir");
  }
}
else {
  
  #print STDERR "svn switch --revision $revision $new_url $dir\n";
  #exec("svn switch --revision $revision $new_url $dir");
  print STDERR "seems to attemt to update to an unrelated repository. Please move away '$dir' before proceeding\n";
  exit 1;
}



sub split_svn_url {
  my $url = shift;
  if ($url =~ /^(.*)\/(((tags)|(branches)|(trunk))\/(.*))$/) {
   #print STDERR "BASE $1 BRANCH $2\n"; 
   return ($1,$2);
  }
  else {
    #print STDERR "BASE $url BRANCH ''\n"; 
    return ($url,"");
  }
}


