#!/usr/bin/env perl

use strict;
use warnings;
use Cwd qw(realpath);
use File::Spec::Functions qw(catfile);
use File::Basename qw(dirname);

my $pgv_home = $ENV{MALTOOLS_HOME} || realpath(catfile(dirname($0),".."));
my $cmd = shift or die "you must indicate a picard command as the first argument";
my $args_str = join(" ",@ARGV);
unless ($args_str =~ /VALIDATION_STRINGENCY/) {
  $args_str .= " VALIDATION_STRINGENCY=LENIENT";
}

my $jar_file = catfile($pgv_home,'lib','java','picard-commands',$cmd . ".jar");

exec("java -Xmx1000m -jar $jar_file $args_str");
